// 地域数据
const regionsData = [
  { id: 'beijing', name: '北京', code: 'BJ' },
  { id: 'tianjin', name: '天津', code: 'TJ' },
  { id: 'hebei', name: '河北', code: 'HE' },
  { id: 'shanxi', name: '山西', code: 'SX' },
  { id: 'neimenggu', name: '内蒙古', code: 'NM' },
  { id: 'liaoning', name: '辽宁', code: 'LN' },
  { id: 'jilin', name: '吉林', code: 'JL' },
  { id: 'heilongjiang', name: '黑龙江', code: 'HL' },
  { id: 'shanghai', name: '上海', code: 'SH' },
  { id: 'jiangsu', name: '江苏', code: 'JS' },
  { id: 'zhejiang', name: '浙江', code: 'ZJ' },
  { id: 'anhui', name: '安徽', code: 'AH' },
  { id: 'fujian', name: '福建', code: 'FJ' },
  { id: 'jiangxi', name: '江西', code: 'JX' },
  { id: 'shandong', name: '山东', code: 'SD' },
  { id: 'henan', name: '河南', code: 'HN' },
  { id: 'hubei', name: '湖北', code: 'HB' },
  { id: 'hunan', name: '湖南', code: 'HN' },
  { id: 'guangdong', name: '广东', code: 'GD' },
  { id: 'guangxi', name: '广西', code: 'GX' },
  { id: 'hainan', name: '海南', code: 'HI' },
  { id: 'chongqing', name: '重庆', code: 'CQ' },
  { id: 'sichuan', name: '四川', code: 'SC' },
  { id: 'guizhou', name: '贵州', code: 'GZ' },
  { id: 'yunnan', name: '云南', code: 'YN' },
  { id: 'xizang', name: '西藏', code: 'XZ' },
  { id: 'shaanxi', name: '陕西', code: 'SN' },
  { id: 'gansu', name: '甘肃', code: 'GS' },
  { id: 'qinghai', name: '青海', code: 'QH' },
  { id: 'ningxia', name: '宁夏', code: 'NX' },
  { id: 'xinjiang', name: '新疆', code: 'XJ' },
  { id: 'hongkong', name: '香港', code: 'HK' },
  { id: 'macau', name: '澳门', code: 'MO' },
  { id: 'taiwan', name: '台湾', code: 'TW' },
  { id: 'common', name: '通用', code: 'ALL' }
];

module.exports = regionsData;